# fly.toml app configuration file generated for api-inventory-app on 2024-09-14T23:41:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-inventory-app'
primary_region = 'scl'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  APP_NAME='Laravel'
  APP_KEY='base64:7UpkGlDD/hgQC28XfwQ5hRgKTYjDL4APZ8RawBvgFFk='
  APP_DEBUG='true'
  APP_TIMEZONE='UTC'
  APP_URL='http://api.inventory.dev'
  APP_LOCALE='en'
  APP_FALLBACK_LOCALE='en'
  APP_FAKER_LOCALE='en_US'
  APP_MAINTENANCE_DRIVER='file'
  BCRYPT_ROUNDS='12'
  LOG_STACK='single'
  LOG_DEPRECATIONS_CHANNEL='null'
  DB_CONNECTION='pgsql'
  DB_HOST='next-inventory-db.flycast'
  DB_PORT='5432'
  DB_DATABASE='postgres'
  DB_USERNAME='postgres'
  DB_PASSWORD='HMhrRMqW9tzuxDc'
  SESSION_LIFETIME='120'
  SESSION_ENCRYPT='false'
  SESSION_PATH='/'
  SESSION_DOMAIN='null'
  BROADCAST_CONNECTION='log'
  FILESYSTEM_DISK='local'
  QUEUE_CONNECTION='database'
  CACHE_STORE='database'
  CACHE_PREFIX=''
  MEMCACHED_HOST='127.0.0.1'
  REDIS_CLIENT='phpredis'
  REDIS_HOST='127.0.0.1'
  REDIS_PASSWORD='null'
  REDIS_PORT='6379'
  MAIL_MAILER='log'
  MAIL_HOST='127.0.0.1'
  MAIL_PORT='2525'
  MAIL_USERNAME='null'
  MAIL_PASSWORD='null'
  MAIL_ENCRYPTION='null'
  MAIL_FROM_ADDRESS='hello@example.com'
  MAIL_FROM_NAME='${APP_NAME}'
  AWS_ACCESS_KEY_ID=''
  AWS_SECRET_ACCESS_KEY=''
  AWS_DEFAULT_REGION='us-east-1'
  AWS_BUCKET=''
  AWS_USE_PATH_STYLE_ENDPOINT='false'
  VITE_APP_NAME='${APP_NAME}'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

