"use client";
import { IUser } from "@/modules/auth";
import { FormEvent, useState } from "react";
import { useCartStore } from "../store/cart.store";
import { toast } from "sonner";
import { createSale } from "@/modules/sale";
import { Button, Input } from "@nextui-org/react";
import { currencyFormatter } from "@/utils/currencyFormatter";

interface Props {
    user: IUser;
}

export function CheckoutForm({ user }: Props) {
    const [isLoading, setIsLoading] = useState(false);
    const { total, cart, clearCart } = useCartStore();

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault()
        setIsLoading(true);

        const { clientName } = e.target as HTMLFormElement;

        if (clientName.value.trim() === "") {
            toast.warning("The name of the client is required");
            setIsLoading(false)
            return
        }

        const formData = new FormData();

        formData.append("clientName", clientName.value);
        formData.append("userName", user.name);
        formData.append("userEmail", user.email);
        formData.append("user_id", `${user.id}`);
        formData.append("total", `${total}`);
        formData.append("cart", JSON.stringify(cart))


        const { data, error } = await createSale(formData);

        if (error) {
            toast.error(error);
            setIsLoading(false);
            return;
        }


        toast.success(data?.message);

        clearCart();

        setIsLoading(false);
    }

    return (
        <div className="col-span-3">
            <div className='mb-6'>
                <h2 className='text-2xl font-bold'>Generate Sale</h2>
                <p>Complete the details of the sale</p>
            </div>

            <form onSubmit={handleSubmit} className='checkout__form'>
                <Input
                    isRequired
                    size='sm'
                    label="Client"
                    placeholder='Enter client name'
                    name='clientName'
                />

                <p className='font-semibold text-xl'>Total: {currencyFormatter(`${total}`)}</p>

                <p>This sale will be generated by: {user.name}</p>

                <Button
                    type='submit'
                    className='btn_primary'
                    variant="shadow"
                    fullWidth
                    isLoading={isLoading}
                    isDisabled={isLoading}

                >
                    Generate Sale
                </Button>

                <Button
                    type='button'
                    color="danger"
                    variant="shadow"
                    fullWidth
                    onClick={clearCart}

                >
                    Clear Cart
                </Button>

            </form>

        </div>
    )
}